server:
  port: 8089
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ca_education?useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Jackson配置
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    #日期时区
    time-zone: GMT+8
    #返回Null不显示
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.itcast.education.model

#swagger 配置
swagger:
  title: CaEducation测试Swagger APIs
  desc: 基于springBoot编写的RESful-API，CaEducation的后端swagger接口，统一在该平台示例。
  version: 0.0.1.SNAPSHOT
  termsOfServiceUrl: javascript:void(0)
  #许可证
  license: 涨涨开发
  #许可证网站
  licenseUrl: javascript:void(0)
  #API所在的包
  basePackage: com.itcast.education.controller
  #组名
  groupName: baseModule
  #作者信息
  contactName: zheng.zhang
  contactUrl: https://github.com/EternityBQQ/CaEducation.git
  contactEmail: 2215751025@qq.com
logging:
  file:
    path: C:/MyFile/Java/workspace/log
